spring.output.ansi.enabled=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/microloans
spring.datasource.username=data
spring.datasource.password=data1234567890
spring.sql.init.mode=always
spring.sql.init.order=1
spring.sql.init.data-order=2
vaadin.launch-browser=true
vaadin.url-mapping=/ui/*
vaadin.frontend.url=/frontend/*
spring.application.name=microloans service

server.port=8080
format.pattern.date=yyyy-MM-dd
format.pattern.datetime=yyyy-MM-dd HH:mm:ss
spring.mvc.format.date-time=iso
