# =============================
# APPLICATION CONFIGURATION
# =============================
spring.application.name=microloans-service
server.port=8080
spring.output.ansi.enabled=always
spring.thymeleaf.cache=false
logging.level.org.springframework.security=DEBUG

# =============================
# DATABASE CONFIGURATION
# =============================
spring.datasource.url=jdbc:postgresql://localhost:5432/microloans
spring.datasource.username=data
spring.datasource.password=data1234567890
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# Hibernate/JPA Configuration
# =============================
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# =============================
# Database initialization
# =============================
spring.sql.init.mode=always
spring.sql.init.order=1
spring.sql.init.data-order=2

# =============================
# VAADIN CONFIGURATION
# =============================
vaadin.launch-browser=true
vaadin.url-mapping=/*
vaadin.frontend.url=/frontend/*
vaadin.productionMode=false
vaadin.excludePackages=com.example.unused
vaadin.whitelisted-packages=ru.hometask

# =============================
# FORMATTING CONFIGURATION
# =============================
spring.mvc.format.date-time=iso
format.pattern.date=yyyy-MM-dd
format.pattern.datetime=yyyy-MM-dd HH:mm:ss

# =============================
# SECURITY (EXAMPLE)
# =============================
# spring.security.user.name=admin
# spring.security.user.password=admin
# spring.security.user.roles=ADMIN


#??? ?????:
#?????????? vaadin.productionMode=true
#???????? ddl-auto=validate
#????????? show-sql